# Base image nhẹ
FROM node:20-alpine

# Thiết lập working directory
WORKDIR /app

# Copy dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm ci

# Copy mã nguồn
COPY . .

# Expose port
EXPOSE 3001

CMD ["npm", "start"]